name: sandvich
description: TF2 content aggregator

publish_to: 'none'

version: 2.0.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  hive: ^1.4.4+1
  flutter_widget_from_html_core: ^0.5.0+3
  time_formatter: ^1.0.0
  url_launcher: ^5.6.0
  share: '>=0.6.5+2 <2.0.0'
  cached_network_image: ^2.3.2+1
  path_provider: ^1.3.0
  toast: ^0.1.5
  material_floating_search_bar: ^0.2.4
  flutter_staggered_grid_view: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Baloo2
      fonts:
        - asset: fonts/Baloo2-Regular.ttf
  assets:
    - images/
